repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.26
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      - id: uv-export
        args: ["--frozen"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.13
    hooks:
        # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff-check
        args: ["--no-fix"]  # optional

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        # excluding here for just a demo
        # exclude: |
        #   (^|/)\.venv/
        #   (^|/)dist/
        #   (^|/)build/
        #   (^|/)node_modules/
        #   (^|/)package\.lock\.json$
        #   (^|/)uv\.lock$
